export interface PortfolioProject {
  id: string;
  order: number;
  title: string;
  url: string;
  urlDisplay: string;
  category: string;
  categoryLabel: string;
  description: string;
  features: [string, string, string];
  image: string;
  filterKey: string;
}

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: 'ds-motor', order: 1,
    title: 'DS Motor',
    url: 'https://www.dsmotor.ro',
    urlDisplay: 'dsmotor.ro',
    category: 'Piese Agricole', categoryLabel: 'Piese Agricole',
    description: 'Website de prezentare pentru business auto cu servicii de inchirieri, service si vanzari de piese agricole.',
    features: ['Plata card + ramburs', 'Soft facturare + curieri', 'Sistem inchirieri utilaje'],
    image: '/imagini/portofoliu/DSMOTOR.RO.webp',
    filterKey: 'website-prezentare',
  },
  {
    id: 'cutia-de-magie', order: 2,
    title: 'Cutia de Magie',
    url: 'https://www.cutiademagie.ro',
    urlDisplay: 'cutiademagie.ro',
    category: 'Accesorii', categoryLabel: 'Accesorii',
    description: 'Magazin online pentru materiale de creatii si cadouri personalizate, optimizat pentru conversii rapide.',
    features: ['Plata cu cardul integrata', 'Soft facturare integrat', 'Integrare curieri'],
    image: '/imagini/portofoliu/CUTIADEMAGIE.RO.webp',
    filterKey: 'magazine-online',
  },
  {
    id: 'atp-autoteile', order: 3,
    title: 'ATP Autoteile',
    url: 'https://www.atp-autoteile.de/de',
    urlDisplay: 'atp-autoteile.de',
    category: 'Auto', categoryLabel: 'Auto',
    description: 'Magazin online de piese si accesorii auto cu filtrare avansata si integrare TecDoc pentru catalogul de piese.',
    features: ['Aplicatie mobila inclusa', 'Filtrare avansata', 'Integrare TecDoc'],
    image: '/imagini/portofoliu/ATPAUTOTEILE.webp',
    filterKey: 'magazine-online',
  },
  {
    id: 'sagra-handmade', order: 4,
    title: 'Sagra Handmade',
    url: 'https://www.sagrahandmade.com',
    urlDisplay: 'sagrahandmade.com',
    category: 'Fashion', categoryLabel: 'Fashion',
    description: 'Platforma eCommerce pentru produse handmade unice, cu experienta de cumparare emotionala in doua limbi.',
    features: ['2 limbi (RO/EN)', 'Integrare BT iPay', 'Filtrare avansata'],
    image: '/imagini/portofoliu/SAGRAHANDMADE.COM.webp',
    filterKey: 'magazine-online',
  },
  {
    id: 'profesorul-de-ai', order: 5,
    title: 'Profesorul de AI',
    url: 'https://www.profesoruldeai.ro',
    urlDisplay: 'profesoruldeai.ro',
    category: 'Educatie', categoryLabel: 'Educatie',
    description: 'Website educational in domeniul AI care explica beneficiile si ghideaza utilizatorii spre utilizare practica.',
    features: ['Plata Stripe integrata', 'Implementare API', 'Optimizare SEO'],
    image: '/imagini/portofoliu/PROFESORULDEAI.RO.webp',
    filterKey: 'educatie',
  },
  {
    id: 'varlan-eisenbau', order: 6,
    title: 'Varlan Eisenbau',
    url: 'https://www.varlan-eisenbau.com',
    urlDisplay: 'varlan-eisenbau.com',
    category: 'Constructii', categoryLabel: 'Constructii',
    description: 'Website pentru companie de constructii industriale cu portofoliu de lucrari si formulare oferta.',
    features: ['Galerie proiecte', 'Integrare Google Ads', 'Formular contact + WhatsApp'],
    image: '/imagini/portofoliu/VARLAN-EISENBAU.COM.webp',
    filterKey: 'constructii',
  },
  {
    id: 'marsal', order: 7,
    title: 'Marsal',
    url: 'https://www.marsal.ro',
    urlDisplay: 'marsal.ro',
    category: 'Mobilier', categoryLabel: 'Mobilier',
    description: 'Magazin online de mobilier premium fabricat in Romania cu sistem de comanda rapida si prezentare detaliata.',
    features: ['Plata card + ramburs', 'SmartBill + curieri', 'Sistem comanda rapida'],
    image: '/imagini/portofoliu/MARSAL.RO.webp',
    filterKey: 'magazine-online',
  },
  {
    id: 'parfumeria-zodiac', order: 8,
    title: 'Parfumeria Zodiac',
    url: 'https://www.parfumeria-zodiac.ro',
    urlDisplay: 'parfumeria-zodiac.ro',
    category: 'Parfumuri', categoryLabel: 'Parfumuri',
    description: 'Magazin online de parfumuri cu navigare simpla, categorii clare si filtrare avansata pe atribute.',
    features: ['Plati card integrate', 'SmartBill + Cargus', 'Filtrare avansata'],
    image: '/imagini/portofoliu/PARFUMERIA-ZODIAC.RO.webp',
    filterKey: 'magazine-online',
  },
  {
    id: 'dental-future', order: 9,
    title: 'Dental Future',
    url: 'https://www.dentalfuture.ro',
    urlDisplay: 'dentalfuture.ro',
    category: 'Educatie', categoryLabel: 'Educatie',
    description: 'Platforma educationala pentru stomatologi cu cursuri moderne de implantologie si sistem de inscrieri.',
    features: ['Formular contact', 'Contact WhatsApp', 'Pagini selectare cursuri'],
    image: '/imagini/portofoliu/DENTALFUTURE.RO.webp',
    filterKey: 'educatie',
  },
  {
    id: 'junior-family', order: 10,
    title: 'Junior Family',
    url: 'https://www.juniorfamily.ro',
    urlDisplay: 'juniorfamily.ro',
    category: 'Stomatologie', categoryLabel: 'Stomatologie',
    description: 'Website pentru servicii medicale stomatologice cu pagini dedicate clinicilor, medicilor si programarilor.',
    features: ['Integrare TIDIO', 'Integrare TBI Bank', 'Pagini clinici + medici'],
    image: '/imagini/portofoliu/JUNIORFAMILY.RO.webp',
    filterKey: 'website-prezentare',
  },
  {
    id: 'ralls', order: 11,
    title: 'RALLS',
    url: 'https://www.ralls.ro',
    urlDisplay: 'ralls.ro',
    category: 'Fashion', categoryLabel: 'Fashion',
    description: 'Platforma eCommerce pentru brand de haine cu design atractiv, produse variabile si structura optimizata.',
    features: ['Plata card integrata', 'Soft facturare integrat', 'Produse variabile'],
    image: '/imagini/portofoliu/RALLS.RO.webp',
    filterKey: 'magazine-online',
  },
  {
    id: 'hontrio', order: 12,
    title: 'Hontrio',
    url: 'https://www.hontrio.com',
    urlDisplay: 'hontrio.com',
    category: 'SaaS', categoryLabel: 'SaaS',
    description: 'Platforma SaaS cu AI pentru optimizarea magazinelor online: automatizare, prevenire comenzi false, SEO.',
    features: ['4 functii principale AI', 'Dashboard modern', 'Platforma internationala'],
    image: '/imagini/portofoliu/HONTRIO.COM.webp',
    filterKey: 'saas',
  },
  {
    id: 'fortas-estate', order: 13,
    title: 'Fortas Estate',
    url: 'https://www.fortasestate.ro',
    urlDisplay: 'fortasestate.ro',
    category: 'Imobiliare', categoryLabel: 'Imobiliare',
    description: 'Platforma imobiliara cu sistem de filtrare avansat, listari detaliate si generare eficienta de lead-uri.',
    features: ['Cautare rapida', 'Filtrare avansata', 'Profil proprietate'],
    image: '/imagini/portofoliu/FORTASESTATE.RO.webp',
    filterKey: 'imobiliare',
  },
  {
    id: 'fabrica-de-acoperisuri', order: 14,
    title: 'Fabrica de Acoperisuri',
    url: 'https://www.fabrica-de-acoperisuri.ro',
    urlDisplay: 'fabrica-de-acoperisuri.ro',
    category: 'Constructii', categoryLabel: 'Constructii',
    description: 'Website pentru servicii complete de acoperisuri cu catalog pachete, fise tehnice si formular personalizat.',
    features: ['Catalog de pachete', 'Formular personalizat', 'Fise tehnice incluse'],
    image: '/imagini/portofoliu/FABRICA-DE-ACOPERISURI.RO.webp',
    filterKey: 'constructii',
  },
  {
    id: 'export-trans', order: 15,
    title: 'Export Trans',
    url: 'https://www.exporttrans.ro',
    urlDisplay: 'exporttrans.ro',
    category: 'Echipamente', categoryLabel: 'Echipamente',
    description: 'Website pentru servicii si echipamente industriale cu specificatii tehnice detaliate si solicitari de oferta.',
    features: ['Formular contact + WhatsApp', 'Card pentru fiecare nacela', 'Optimizare SEO'],
    image: '/imagini/portofoliu/EXPORTTRANS.RO.webp',
    filterKey: 'website-prezentare',
  },
  {
    id: 'apca', order: 16,
    title: 'APCA',
    url: 'https://www.apca.ro',
    urlDisplay: 'apca.ro',
    category: 'Asociatie', categoryLabel: 'Asociatie',
    description: 'Website pentru Asociatia Carosierilor Auto din Romania cu forum, harta interactiva si profiluri membri.',
    features: ['Forum integrat', 'Harta interactiva', 'Profil pentru fiecare membru'],
    image: '/imagini/portofoliu/APCA.RO.webp',
    filterKey: 'website-prezentare',
  },
  {
    id: 'ti-global-import', order: 17,
    title: 'TI Global Import',
    url: 'https://www.tiglobalimport1010.com',
    urlDisplay: 'tiglobalimport1010.com',
    category: 'Metale', categoryLabel: 'Metale',
    description: 'Website multilingv pentru import si distributie materiale industriale cu catalog produse si contact rapid.',
    features: ['3 limbi (RO/EN/FR)', 'Catalog produse', 'Formular + WhatsApp'],
    image: '/imagini/portofoliu/TIGLOBALIMPORT1010.COM.webp',
    filterKey: 'website-prezentare',
  },
  {
    id: 'nemes-car', order: 18,
    title: 'Nemes Car',
    url: 'https://www.nemescar.ro',
    urlDisplay: 'nemescar.ro',
    category: 'Parc Auto', categoryLabel: 'Parc Auto',
    description: 'Platforma pentru vanzari auto cu cautare rapida, filtre intuitive si pagini detaliate per vehicul.',
    features: ['Cautare + filtrare avansata', 'Pagina vehicul detaliata', 'Formular masina la comanda'],
    image: '/imagini/portofoliu/NEMESCAR.RO.webp',
    filterKey: 'auto',
  },
  {
    id: 'meditatii-level-up', order: 19,
    title: 'Meditatii Level Up',
    url: 'https://www.meditatiilevelup.ro',
    urlDisplay: 'meditatiilevelup.ro',
    category: 'Educatie', categoryLabel: 'Educatie',
    description: 'Website pentru centru de meditatii cu profiluri profesori, pachete de pret si formular contact.',
    features: ['Formular + WhatsApp', 'Profil profesori', 'Pachete de pret'],
    image: '/imagini/portofoliu/MEDITATIILEVELUP.RO.webp',
    filterKey: 'educatie',
  },
  {
    id: 'magic-ice', order: 20,
    title: 'Magic Ice',
    url: 'https://www.magic-ice.ro',
    urlDisplay: 'magic-ice.ro',
    category: 'Inghetata', categoryLabel: 'Inghetata',
    description: 'Magazin online pentru un brand pionier al inghetatei in Romania, cu sistem de trepte discount si integratii complete.',
    features: ['Plata card + ramburs', 'SAGA + curieri integrat', 'Sistem trepte discount'],
    image: '/imagini/portofoliu/MAGICICE.RO.webp',
    filterKey: 'magazine-online',
  },
  {
    id: 'carlyon', order: 21,
    title: 'Carlyon',
    url: 'https://www.carlyon.ro',
    urlDisplay: 'carlyon.ro',
    category: 'Inchirieri Auto', categoryLabel: 'Inchirieri Auto',
    description: 'Website de inchirieri auto cu prezentare flota, rezervari rapide si profiluri detaliate per vehicul.',
    features: ['Cautare rapida', 'Plata cu cardul', 'Profil vehicul'],
    image: '/imagini/portofoliu/CARLYON.RO.webp',
    filterKey: 'inchirieri-auto',
  },
  {
    id: 'tim-afvp', order: 22,
    title: 'TIM AFVP',
    url: 'https://www.tim.afvp.ro',
    urlDisplay: 'tim.afvp.ro',
    category: 'Dans', categoryLabel: 'Dans',
    description: 'Website pentru scoala de dans popular cu activitati, cursuri, sistem de inscriere si galerie media.',
    features: ['Formular inscriere', 'WhatsApp + Apel', 'Galerie & Media'],
    image: '/imagini/portofoliu/TIM.AFVP.RO.webp',
    filterKey: 'website-prezentare',
  },
  {
    id: 'inchirieri-auto-arges', order: 23,
    title: 'Inchirieri Auto Arges',
    url: 'https://www.inchirieriautoarges.ro',
    urlDisplay: 'inchirieriautoarges.ro',
    category: 'Inchirieri Auto', categoryLabel: 'Inchirieri Auto',
    description: 'Website de inchirieri auto cu sistem complet de administrare, plata card si pagini vehicul detaliate.',
    features: ['Sistem administrare complet', 'Plata cu cardul', 'Pagina vehicul detaliata'],
    image: '/imagini/portofoliu/INCHIRIERIAUTOARGES.RO.webp',
    filterKey: 'inchirieri-auto',
  },
  {
    id: 'gabs-team', order: 24,
    title: 'Gabs Team',
    url: 'https://www.gabsteam.ro',
    urlDisplay: 'gabsteam.ro',
    category: 'Constructii', categoryLabel: 'Constructii',
    description: 'Website pentru firma de constructii civile si industriale cu portofoliu proiecte si sectiune imobiliara.',
    features: ['Formular + WhatsApp', 'Sectiune imobiliare', 'Portofoliu proiecte'],
    image: '/imagini/portofoliu/GABSTEAM.RO.webp',
    filterKey: 'constructii',
  },
  {
    id: 'un-colt-din-rai', order: 25,
    title: 'Un Colt din Rai',
    url: 'https://www.uncoltdinrai.com',
    urlDisplay: 'uncoltdinrai.com',
    category: 'Servicii', categoryLabel: 'Servicii',
    description: 'Website pentru servicii funerare cu pagini dedicate, catalog accesorii si blog informativ.',
    features: ['Catalog produse', 'Blog integrat', 'Formular + WhatsApp'],
    image: '/imagini/portofoliu/UNCOLTDINRAI.COM.webp',
    filterKey: 'website-prezentare',
  },
];

export const FILTER_CATEGORIES = [
  { key: 'toate', label: 'Toate' },
  { key: 'magazine-online', label: 'Magazine Online' },
  { key: 'website-prezentare', label: 'Website Prezentare' },
  { key: 'auto', label: 'Auto' },
  { key: 'imobiliare', label: 'Imobiliare' },
  { key: 'educatie', label: 'Educatie' },
  { key: 'constructii', label: 'Constructii' },
  { key: 'saas', label: 'SaaS' },
  { key: 'inchirieri-auto', label: 'Inchirieri Auto' },
];
